# Generated by Django 5.2.11 on 2026-02-22 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pg_host', models.CharField(max_length=255)),
                ('pg_port', models.IntegerField(default=5432)),
                ('pg_database', models.CharField(max_length=100)),
                ('pg_user', models.CharField(default='simona_user', max_length=100)),
                ('pg_password', models.CharField(max_length=255)),
                ('destination_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('s3', 'Amazon S3')], max_length=20)),
                ('drive_folder_url', models.URLField(blank=True, null=True)),
                ('google_api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('s3_bucket_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s3_region', models.CharField(blank=True, max_length=50, null=True)),
                ('s3_access_key', models.CharField(blank=True, max_length=100, null=True)),
                ('s3_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
