# Generated by Django 5.2.11 on 2026-02-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_connector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('timestamp_column', models.CharField(default='updated_at', max_length=100)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('success', 'Exitoso'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='core.connector')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('connector', 'table_name')},
            },
        ),
    ]
