# Generated by Django 5.2.11 on 2026-02-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_googledrivetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='google_api_key',
        ),
    ]
