# Generated by Django 5.2.11 on 2026-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_connector_google_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='sync_frequency',
            field=models.IntegerField(choices=[(5, '5 minutos'), (15, '15 minutos'), (30, '30 minutos'), (60, '1 hora'), (360, '6 horas'), (1440, '24 horas')], default=60, help_text='Frecuencia de sincronización en minutos'),
        ),
    ]
