# Generated by Django 5.2.11 on 2026-03-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_connector_sync_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Ejecutando'), ('success', 'Exitoso'), ('partial', 'Parcial'), ('failed', 'Fallido')], default='running', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático')], default='manual', max_length=20)),
                ('tables_synced', models.IntegerField(default=0)),
                ('tables_failed', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_executions', to='core.connector')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
