# Generated by Django 5.2.11 on 2026-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_syncexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='last_schema',
            field=models.TextField(blank=True, help_text='Lista de columnas de la última sincronización (JSON)', null=True),
        ),
    ]
