# Generated by Django 5.2.11 on 2026-03-08 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_synctask_last_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la limpieza', max_length=100)),
                ('pg_host', models.CharField(max_length=255)),
                ('pg_port', models.IntegerField(default=5432)),
                ('pg_database', models.CharField(max_length=100)),
                ('pg_user', models.CharField(max_length=100)),
                ('pg_password', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=100)),
                ('timestamp_column', models.CharField(help_text='Campo timestamp para evaluar antigüedad', max_length=100)),
                ('retention_months', models.IntegerField(default=0, help_text='Meses de retención (0-12)')),
                ('retention_days', models.IntegerField(default=7, help_text='Días de retención (0-365)')),
                ('retention_hours', models.IntegerField(default=0, help_text='Horas de retención (0-24)')),
                ('cleanup_frequency', models.IntegerField(choices=[(60, '1 hora'), (360, '6 horas'), (720, '12 horas'), (1440, '24 horas')], default=1440, help_text='Frecuencia de limpieza en minutos')),
                ('is_active', models.BooleanField(default=True)),
                ('last_cleanup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleanupExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Ejecutando'), ('success', 'Exitoso'), ('failed', 'Fallido')], default='running', max_length=20)),
                ('rows_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.cleanuptask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
