# Generated by Django 5.2.11 on 2026-03-10 04:24

from django.db import migrations, models


def encrypt_existing_passwords(apps, schema_editor):
    """Cifra las contraseñas existentes"""
    from core.encryption import encrypt_password
    
    Connector = apps.get_model('core', 'Connector')
    CleanupTask = apps.get_model('core', 'CleanupTask')
    
    # Cifrar contraseñas de conectores
    for connector in Connector.objects.all():
        if connector.pg_password and not connector.pg_password.startswith('gAAAAA'):
            connector.pg_password = encrypt_password(connector.pg_password)
        if connector.s3_secret_key and not connector.s3_secret_key.startswith('gAAAAA'):
            connector.s3_secret_key = encrypt_password(connector.s3_secret_key)
        connector.save()
    
    # Cifrar contraseñas de tareas de limpieza
    for task in CleanupTask.objects.all():
        if task.pg_password and not task.pg_password.startswith('gAAAAA'):
            task.pg_password = encrypt_password(task.pg_password)
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cleanuptask_cleanupexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanuptask',
            name='pg_password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='connector',
            name='pg_password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='connector',
            name='s3_secret_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(encrypt_existing_passwords, reverse_code=migrations.RunPython.noop),
    ]
